#
# Vivado (TM) v2016.3 (64-bit)
#
# FRACTCAM_D512XK80.tcl: Tcl script for re-creating project 'FRACTCAM_D512XK80'
#
# Generated by Vivado on Mon Aug 03 20:57:21 +0500 2020
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (FRACTCAM_D512XK80.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/fractcam1x6.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/and6.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/mux5bit.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/comparator.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/srl_rf.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/DBLOCK32X5.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/Demux.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/andD6.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/counter_srl.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/DBLOCK64x5.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/counter.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/cont_signal.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/compare.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/register.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/match_reduction.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/frac_tcam.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/update_logic.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/dummy_key_rules.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/top.v"
#    "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.srcs/constrs_1/imports/CODE/fanout.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "FRACTCAM_D512XK80.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project FRACTCAM_D512XK80 ./FRACTCAM_D512XK80 -part xc7v2000tfhg1761-2L

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects FRACTCAM_D512XK80]
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "read write" $obj
set_property "ip_output_repo" "F:/Educations/RESEARCHACTIVITY/Networkhardware/TCAM/FracTCAM/TVLSI_REV/opensource/FRACTCAM_D512XK80/FRACTCAM_D512XK80.cache/ip" $obj
set_property "part" "xc7v2000tfhg1761-2L" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "xsim.array_display_limit" "64" $obj
set_property "xsim.trace_limit" "65536" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/fractcam1x6.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/and6.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/mux5bit.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/comparator.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/srl_rf.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/DBLOCK32X5.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/Demux.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/andD6.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/counter_srl.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/DBLOCK64x5.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/counter.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/cont_signal.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/compare.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/register.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/match_reduction.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/frac_tcam.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/updatelogic/update_logic.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/dummy_key_rules.v"]"\
 "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/sources_1/imports/CODE/fractacam_w80/top.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "top" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/FRACTCAM_D512XK80.srcs/constrs_1/imports/CODE/fanout.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/FRACTCAM_D512XK80.srcs/constrs_1/imports/CODE/fanout.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "top" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7v2000tfhg1761-2L -flow {Vivado Synthesis 2016} -strategy "nodspblock" -constrset constrs_1
} else {
  set_property strategy "nodspblock" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7v2000tfhg1761-2L" $obj
set_property "steps.synth_design.args.max_dsp" "0" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7v2000tfhg1761-2L -flow {Vivado Implementation 2016} -strategy "area_optimized" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "area_optimized" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7v2000tfhg1761-2L" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:FRACTCAM_D512XK80"
